In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([ 0.02065234,  0.41968709, -0.35918504, -0.76643085,  0.05039734,
        0.537762  ,  0.15302491, -0.81946821,  0.00754455,  0.12519247,
       -0.26767756,  0.13810289, -0.16389889, -0.23210311,  1.09039624,
        0.10652802,  0.49139649, -0.45546144,  0.55113562, -1.42575919,
       -0.09390495, -0.02802537, -0.4077931 ,  0.5189366 ,  0.71112532,
       -0.17866356, -0.87272423, -0.24718505,  0.34304117,  0.0178749 ,
        0.42011593,  0.14274679, -0.00285235, -1.89653951, -0.38414739,
        0.69215541, -0.17547727, -0.35726252, -0.67608607,  0.63420645,
        0.29862212,  0.39502343,  0.76093847,  2.09902515,  0.9248795 ,
       -0.3374003 ,  0.21599363, -0.61530354, -0.54449942,  0.8628056 ,
       -1.55787559,  0.18410519,  1.30111049,  1.22027292, -0.15562216,
        1.77783599,  0.20411648, -0.00617205,  0.31786704, -2.75978078,
        0.16497265,  1.33443248, -1.8177726 , -1.30719217,  0.69607707,
       -0.45235192, -0.04538744,  2.27350692, -0.00459078,  1.55

In [4]:
A = 10 * A + 50

In [5]:
A

array([50.20652337, 54.19687088, 46.4081496 , 42.33569152, 50.50397335,
       55.37761998, 51.53024908, 41.80531789, 50.07544553, 51.25192471,
       47.32322438, 51.38102888, 48.36101106, 47.67896892, 60.90396238,
       51.06528017, 54.91396493, 45.44538556, 55.51135618, 35.7424081 ,
       49.0609505 , 49.71974632, 45.92206901, 55.18936603, 57.11125316,
       48.21336435, 41.27275768, 47.52814947, 53.4304117 , 50.17874896,
       54.20115927, 51.42746794, 49.97147649, 31.03460488, 46.15852614,
       56.92155415, 48.24522726, 46.42737485, 43.23913926, 56.34206451,
       52.98622115, 53.95023434, 57.60938471, 70.99025145, 59.24879499,
       46.62599696, 52.15993634, 43.8469646 , 44.55500579, 58.62805596,
       34.42124413, 51.84105191, 63.01110487, 62.20272917, 48.4437784 ,
       67.77835994, 52.04116479, 49.93827949, 53.17867038, 22.40219219,
       51.64972651, 63.34432478, 31.82227403, 36.92807825, 56.96077072,
       45.47648085, 49.54612559, 72.73506917, 49.95409224, 65.59

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[50.20652337, 54.19687088, 46.4081496 , 42.33569152, 50.50397335,
        55.37761998, 51.53024908, 41.80531789, 50.07544553, 51.25192471,
        47.32322438, 51.38102888, 48.36101106, 47.67896892, 60.90396238,
        51.06528017, 54.91396493, 45.44538556, 55.51135618, 35.7424081 ],
       [49.0609505 , 49.71974632, 45.92206901, 55.18936603, 57.11125316,
        48.21336435, 41.27275768, 47.52814947, 53.4304117 , 50.17874896,
        54.20115927, 51.42746794, 49.97147649, 31.03460488, 46.15852614,
        56.92155415, 48.24522726, 46.42737485, 43.23913926, 56.34206451],
       [52.98622115, 53.95023434, 57.60938471, 70.99025145, 59.24879499,
        46.62599696, 52.15993634, 43.8469646 , 44.55500579, 58.62805596,
        34.42124413, 51.84105191, 63.01110487, 62.20272917, 48.4437784 ,
        67.77835994, 52.04116479, 49.93827949, 53.17867038, 22.40219219],
       [51.64972651, 63.34432478, 31.82227403, 36.92807825, 56.96077072,
        45.47648085, 49.54612559, 72.73506917, 4

In [9]:
A.reshape(100, 1)

array([[50.20652337],
       [54.19687088],
       [46.4081496 ],
       [42.33569152],
       [50.50397335],
       [55.37761998],
       [51.53024908],
       [41.80531789],
       [50.07544553],
       [51.25192471],
       [47.32322438],
       [51.38102888],
       [48.36101106],
       [47.67896892],
       [60.90396238],
       [51.06528017],
       [54.91396493],
       [45.44538556],
       [55.51135618],
       [35.7424081 ],
       [49.0609505 ],
       [49.71974632],
       [45.92206901],
       [55.18936603],
       [57.11125316],
       [48.21336435],
       [41.27275768],
       [47.52814947],
       [53.4304117 ],
       [50.17874896],
       [54.20115927],
       [51.42746794],
       [49.97147649],
       [31.03460488],
       [46.15852614],
       [56.92155415],
       [48.24522726],
       [46.42737485],
       [43.23913926],
       [56.34206451],
       [52.98622115],
       [53.95023434],
       [57.60938471],
       [70.99025145],
       [59.24879499],
       [46

In [10]:
A = A.reshape(100, 1)

In [11]:
A

array([[50.20652337],
       [54.19687088],
       [46.4081496 ],
       [42.33569152],
       [50.50397335],
       [55.37761998],
       [51.53024908],
       [41.80531789],
       [50.07544553],
       [51.25192471],
       [47.32322438],
       [51.38102888],
       [48.36101106],
       [47.67896892],
       [60.90396238],
       [51.06528017],
       [54.91396493],
       [45.44538556],
       [55.51135618],
       [35.7424081 ],
       [49.0609505 ],
       [49.71974632],
       [45.92206901],
       [55.18936603],
       [57.11125316],
       [48.21336435],
       [41.27275768],
       [47.52814947],
       [53.4304117 ],
       [50.17874896],
       [54.20115927],
       [51.42746794],
       [49.97147649],
       [31.03460488],
       [46.15852614],
       [56.92155415],
       [48.24522726],
       [46.42737485],
       [43.23913926],
       [56.34206451],
       [52.98622115],
       [53.95023434],
       [57.60938471],
       [70.99025145],
       [59.24879499],
       [46

In [ ]:
# Array 生成方式 (一) 

xy = [[x,y] for x in range(10) for y in range(5)]

In [14]:
xy = np.array(xy)

In [15]:
xy

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [7, 0],
       [7, 1],
       [7, 2],
       [7, 3],
       [7, 4],
       [8, 0],
       [8, 1],
       [8, 2],
       [8, 3],
       [8, 4],
       [9, 0],
       [9, 1],
       [9, 2],
       [9, 3],
       [9, 4]])

# Array 生成方式(二)

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])