In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p = [1096.95, 596.95, 896.95]

In [3]:
c = 30.1

In [4]:
prices = np.array(p)

In [5]:
prices

array([1096.95,  596.95,  896.95])

In [6]:
print(prices)

[1096.95  596.95  896.95]


In [15]:
prices * c

array([33018.195, 17968.195, 26998.195])

In [ ]:
#算加權成績
grades = np.array([85,70,90])

In [9]:
weights = np.array([0.3,0.4,0.3])

In [10]:
g = grades * weights

In [11]:
g

array([25.5, 28. , 27. ])

In [12]:
g.sum()

80.5

In [13]:
np.dot(grades,weights)

80.5

#算全班成績

In [17]:
grades = np.array([[85,70,90], [70,65,80], [80,90,90],[60,65,70]])

In [18]:
grades

array([[85, 70, 90],
       [70, 65, 80],
       [80, 90, 90],
       [60, 65, 70]])

In [19]:
weights = np.array([0.3, 0.4, 0.3])

In [20]:
np.dot(grades, weights)

array([80.5, 71. , 87. , 65. ])

In [21]:
L = np.array([3, 5, 7, 9])

In [22]:
L * 3

array([ 9, 15, 21, 27])